name: publish
on:
  push:
    branches: [ main ]
jobs:
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        if: steps.release.outputs.released == 'true'
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
