name: tests
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Pre-Commit

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setups Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Project
        run: uv sync --group dev
      - name: Run Pre-Commit
        run: uv run pre-commit run --all-files
  test:
    runs-on: ${{ matrix.os }}
    needs: [lint]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Project
        run: uv sync --group dev
      - name: Run CI Tests
        run: uv run pytest -v -x -p no:warnings --cov-report term-missing --cov=.
